[package]
name = "drift_meter"
version = "0.1.0"
authors = ["Simon Waloschek <simon.waloschek@posteo.de>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2"
chfft = "0.2.4"
ndarray = "0.11.2"
